run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec
    - gosimple
    - bodyclose
    - noctx
    - thelper
    - prealloc
    - misspell
    - exportloopref

linters-settings:
  errcheck:
    exclude-functions:
      - os.Exit

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
